Update config.json (#9069)
* Update config.json

add various scams
```
    "1inch.boltboxhosting.com",
    "1inch.exchange.smekda.tv",
    "1inch.forkfights.com",
    "1inch.forkflict.com",
    "1inch.hcfspinal.com",
    "1inch.io-swap.promotion.cidatur.com.br",
    "1inch.legacybrandltd.com",
    "accounts-coinbase.edns.biz",
    "accounts.coinbase.u4fa.us",
    "accounts.updates-coinbase.support.u4fa.us",
    "airdrop.aptosıabs.com",
    "app-login.coinbase-account.u4fa.us",
    "app.1inch.boltboxhosting.com",
    "app.1inch.forkfights.com",
    "app.1inch.forkflict.com",
    "app.1inch.hcfspinal.com",
    "app.1inch.homeinsuranceclaimsolutions.com",
    "app.1inch.legacybrandltd.com",
    "app.1inch.retireeslife.com",
    "app.1inch.slowtravelmyanmar.com",
    "aptosıabs.com",
    "aquabitpowercoin-yui.finance",
    "assetsnetworkledger.net",
    "assignix.com",
    "blockchainsolvers.com",
    "blockstakweb3.com",
    "blockweb3connectwallet.com",
    "bt-mining.com",
    "coinbase-securesign.servebeer.com",
    "coinbase-signin.com",
    "coinbase-wallet.4tich.com.co",
    "coinbase-wallet.com.cn",
    "coinbase-wallet.luthgit.com",
    "coinbase-wallet.nemaplc.com",
    "coinbase-wallet.org.cn",
    "coinbase-wallet.store",
    "coinbase-walletmarkettv.com",
    "coinbase.wallet.metpos.net",
    "coinbasecoldwallet.com",
    "coinbasedefi.cloud",
    "coinbasewallet.com.cn",
    "coinbasewalletaccount.com",
    "coinsbit-wallet.cf",
    "coinsbit-wallet.ga",
    "coinsbit-wallet.tk",
    "connecttodapp.website",
    "cryptosfix.webflow.io",
    "customersupportteam.net",
    "dappssynchronize.pages.dev",
    "dappswallets.schlimited.com",
    "dgswalletconnect.com",
    "doa-giveaway.online",
    "docs-pollygonnetwork.com",
    "ethereum-eth.xyz",
    "ethereum-gambling.com",
    "ethereum-ksm.com",
    "ethereum-ldo.com",
    "ethereum-m.com",
    "ethereum-mining.info",
    "ethereum-mixer.cc",
    "ethereum-tvk.com",
    "ethereum-vip.xyz",
    "ethers-airdrops.io",
    "exchange.pancakeswap.finances.preflight.ir",
    "free-ethereum.ru",
    "freeairdropcrypto.com",
    "freeethereum.xyz",
    "io-team.support",
    "krakenexjk.com",
    "krakenexjl.com",
    "krakenexjm.com",
    "krakenexjn.com",
    "krakenexjo.com",
    "krakenexjp.com",
    "krakenexjq.com",
    "krakenexjr.com",
    "krakenexjs.com",
    "krakenexjt.com",
    "krakenexju.com",
    "krakenexjv.com",
    "krakenexjw.com",
    "krakenexjx.com",
    "krakenexjy.com",
    "krakenexjz.com",
    "krakenexka.com",
    "krakenexkb.com",
    "krakenexkc.com",
    "krakenexkd.com",
    "krakenexke.com",
    "krakenexkf.com",
    "krakenexkg.com",
    "krakenexkh.com",
    "krakenexki.com",
    "krakenexkj.com",
    "krakenexkk.com",
    "krakenexkl.com",
    "krakenexkm.com",
    "krakenexkn.com",
    "krakenexko.com",
    "krakenexkp.com",
    "krakenexkq.com",
    "krakenexkr.com",
    "krakenexks.com",
    "krakenexkt.com",
    "krakenexku.com",
    "krakenexkv.com",
    "krakenexkw.com",
    "krakenexkx.com",
    "krakenexky.com",
    "krakenexkz.com",
    "krakenexla.com",
    "krakenexlb.com",
    "krakenexlc.com",
    "krakenexld.com",
    "krakenexle.com",
    "krakenexlf.com",
    "krakenexlg.com",
    "krakenexlh.com",
    "krakenexli.com",
    "krakenexlj.com",
    "krakenexlk.com",
    "krakenexll.com",
    "krakenexlm.com",
    "krakenexln.com",
    "krakenexlo.com",
    "krakenexlp.com",
    "krakenexlq.com",
    "krakenexlr.com",
    "krakenexls.com",
    "krakenexlt.com",
    "krakenexlu.com",
    "krakenexlv.com",
    "krakenexlw.com",
    "krakenexlx.com",
    "krakenexly.com",
    "krakenexlz.com",
    "krakenexma.com",
    "krakenexmb.com",
    "krakenfinancial.co",
    "lidio.online",
    "login.coinbase-signin.com",
    "login.coinbasewalletsupport.com",
    "luckyblockapp.online",
    "mainetwallet.com",
    "manualresolve247.com",
    "metamask.faviconkit.com",
    "metamask.io-1s2r7.dommespace.com.br",
    "metamask.io-defi-web3-dapps-and-nfts.dommespace.com.br",
    "metamask.io.account.verification.update.watch2buy.com",
    "metamask.iomoz-extension.gorsesmk.com",
    "metamask.iomoz-extension.mack-io.com",
    "metamask.iomoz-extension.metmev.com",
    "metamask.metimes.id",
    "metamask.name",
    "metamask.wallet.klaytntoken.com",
    "metamaskb.com",
    "metamaskgrants.org",
    "metamaskhelp.shop",
    "metamasks.life",
    "minexcoin.app",
    "multchainvalidator.com",
    "multichain-rectify.com",
    "myetherwallet-mew.ml",
    "myetherwalletb.com",
    "mywalletdappvalidation.online",
    "netassetfix.com",
    "nftlaunch-defi.com",
    "nodeorbit.online",
    "pancakeswap-finances.digital",
    "pancakeswap.finance.tradeswaps.in",
    "pancakeswap.finances.andrewlumbert.com",
    "pancakeswap.finances.motorbroad.com",
    "pancakeswap.finances.swoptokenx.com",
    "pancakeswap.host",
    "pancakeswapis.com",
    "pancakeswaps.finance",
    "pancakeswep.click.peronagor.com",
    "pancakeswope.financial",
    "pancakeswvaq.com",
    "pandagirl.online",
    "payuethereum.com",
    "pro-neutral.net",
    "prosupport-coinbase.com",
    "recovery.specialartshop.com",
    "report-coinbaseaccounts.com",
    "schlimited.com",
    "signin-coinbase.secure82-cloeorde.com",
    "specialartshop.com",
    "synchronizeconnectssn.com",
    "syncwebdigital.com",
    "tokenfly-drop.com",
    "trusfund.net",
    "trusfunds.com",
    "unbn.online",
    "uniswap-exchange.cloud",
    "uniswap-exchange.com",
    "uniswap-exchenge.com",
    "uniswap-onlinie.com",
    "uniswap-ui-fork.pages.dev",
    "uniswap.bet",
    "uniswap.blue",
    "uniswap.coach",
    "uniswap.coffee",
    "uniswap.education",
    "uniswap.fashion",
    "uniswap.gmbh",
    "uniswap.info.pl",
    "uniswap.institute",
    "uniswap.land",
    "uniswap.lt",
    "uniswap.markets",
    "uniswap.mxi.cloud",
    "uniswap.net.pl",
    "uniswap.one",
    "uniswap.onl",
    "uniswap.pet",
    "uniswap.pw",
    "uniswap.studio",
    "uniswap.tf",
    "uniswap.tokyo",
    "uniswap.tours",
    "uniswap.us",
    "uniswap.works",
    "uniswapav.com",
    "uniswapav.org",
    "uniswapcoin.store",
    "uniswapi.tech",
    "uniswapuni.com",
    "universalresolution.net",
    "us-coinbasewallet.com",
    "verify-coinbase.luthgit.com",
    "walletconnect.nodequery.online",
    "walleterrorfixing.netlify.app",
    "walletloginconnect.square.site",
    "wwvw-kraken-it.space",
    "wwvw-kraken-it.xyz",
```

* Update config.json

Fix punycode
```
      'airdrop.aptosıabs.com'
      'airdrop.xn--aptosabs-xkb.com'
      'aptosıabs.com'
      'xn--aptosabs-xkb.com'
```  

Remove duplicate entries (overlap)
```
Error: domain "1inch.boltboxhosting.com" is duplicated. Domains can only appear in list once
Error: domain "1inch.forkfights.com" is duplicated. Domains can only appear in list once
Error: domain "1inch.forkflict.com" is duplicated. Domains can only appear in list once
Error: domain "1inch.hcfspinal.com" is duplicated. Domains can only appear in list once
Error: domain "1inch.io-swap.promotion.cidatur.com.br" is duplicated. Domains can only appear in list once
Error: domain "1inch.legacybrandltd.com" is duplicated. Domains can only appear in list once
Error: domain "airdrop.aptosıabs.com" is encoded in punycode
Error: domain "app.1inch.boltboxhosting.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.forkfights.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.forkflict.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.hcfspinal.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.homeinsuranceclaimsolutions.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.retireeslife.com" is duplicated. Domains can only appear in list once
Error: domain "app.1inch.slowtravelmyanmar.com" is duplicated. Domains can only appear in list once
Error: domain "aptosıabs.com" is encoded in punycode
Error: domain "coinbase-wallet.com.cn" is duplicated. Domains can only appear in list once
Error: domain "coinbase-wallet.org.cn" is duplicated. Domains can only appear in list once
Error: domain "coinbase-wallet.store" is duplicated. Domains can only appear in list once
Error: domain "coinbasedefi.cloud" is duplicated. Domains can only appear in list once
Error: domain "coinbasewallet.com.cn" is duplicated. Domains can only appear in list once
Error: domain "dappswallets.schlimited.com" is duplicated. Domains can only appear in list once
Error: domain "ethereum-ksm.com" is duplicated. Domains can only appear in list once
Error: domain "ethereum-ldo.com" is duplicated. Domains can only appear in list once
Error: domain "ethereum-tvk.com" is duplicated. Domains can only appear in list once
Error: domain "ethers-airdrops.io" is duplicated. Domains can only appear in list once
Error: domain "metamask.faviconkit.com" is duplicated. Domains can only appear in list once
Error: domain "metamask.io.account.verification.update.watch2buy.com" is duplicated. Domains can only appear in list once
Error: domain "metamask.iomoz-extension.metmev.com" is duplicated. Domains can only appear in list once
Error: domain "metamask.metimes.id" is duplicated. Domains can only appear in list once
Error: domain "metamask.name" is duplicated. Domains can only appear in list once
Error: domain "metamaskb.com" is duplicated. Domains can only appear in list once
Error: domain "metamaskhelp.shop" is duplicated. Domains can only appear in list once
Error: domain "metamasks.life" is duplicated. Domains can only appear in list once
Error: domain "myetherwallet-mew.ml" is duplicated. Domains can only appear in list once
Error: domain "myetherwalletb.com" is duplicated. Domains can only appear in list once
Error: domain "pancakeswap-finances.digital" is duplicated. Domains can only appear in list once
Error: domain "pancakeswap.finances.andrewlumbert.com" is duplicated. Domains can only appear in list once
Error: domain "pancakeswaps.finance" is duplicated. Domains can only appear in list once
Error: domain "pancakeswep.click.peronagor.com" is duplicated. Domains can only appear in list once
Error: domain "pancakeswope.financial" is duplicated. Domains can only appear in list once
Error: domain "pancakeswvaq.com" is duplicated. Domains can only appear in list once
Error: domain "report-coinbaseaccounts.com" is duplicated. Domains can only appear in list once
Error: domain "uniswap-exchange.com" is duplicated. Domains can only appear in list once
Error: domain "uniswap-exchenge.com" is duplicated. Domains can only appear in list once
Error: domain "uniswap-onlinie.com" is duplicated. Domains can only appear in list once
Error: domain "uniswap-ui-fork.pages.dev" is duplicated. Domains can only appear in list once
Error: domain "uniswap.bet" is duplicated. Domains can only appear in list once
Error: domain "uniswap.mxi.cloud" is duplicated. Domains can only appear in list once
Error: domain "uniswapi.tech" is duplicated. Domains can only appear in list once
```

* Update config.json

fix fat finger missed double quotes (broke json)

* Create config.json

fix fat finger missed double quotes (broke json)

* Update config.json

remove dupes
```
Error: domain "1inch.io-swap.promotion.cidatur.com.br" is duplicated. Domains can only appear in list once
Error: domain "1inch.legacybrandltd.com" is duplicated. Domains can only appear in list once
Error: domain "airdrop.xn--aptosabs-xkb.com" is duplicated. Domains can only appear in list once
Error: domain "metamaskhelp.shop" is duplicated. Domains can only appear in list once
Error: domain "metamasks.life" is duplicated. Domains can only appear in list once
Error: domain "xn--aptosabs-xkb.com" is duplicated. Domains can only appear in list once
```

* Update config.json

Add one random junk "giveaway" to force CI/CD retest 👀
```
"2xmusketh.com",
```